when:
  - event: ["push", "pull_request"]
    branch: ["main"]

engine: microvm
image: nixos

caches:
  https://tsirysndr.cachix.org: "tsirysndr.cachix.org-1:fbGYj/T8+9oqrF2c3EaQ33lMqZdb5n81Mk2jRE+C4wA="

dependencies:
  - cargo
  - rustc
  - rustfmt
  - gcc
  - pkg-config
  - alsa-lib

steps:
  - name: nix build
    command: |
      XDG_CACHE_HOME=/tmp/nix-cache nix --extra-experimental-features 'nix-command flakes' build .#default --print-build-logs --fallback
      ls -l result/bin

