when:
  - event: ["push", "pull_request"]
    branch: ["main"]

engine: microvm
image: nixos

dependencies:
  - cargo
  - rustc
  - rustfmt
  - gcc
  - pkg-config
  - alsa-lib
  - bun
  - nodejs
  - dbus
  - protobuf

steps:
  - name: build webui
    command: |
      cd web
      bun install --frozen-lockfile
      bun run build

  - name: nix build
    command: |
      XDG_CACHE_HOME=/tmp/nix-cache nix --extra-experimental-features 'nix-command flakes' build .#default --print-build-logs --fallback
      ls -l result/bin

