pub const TAGS: &[&str] = &[
    "pop",
    "music",
    "news",
    "rock",
    "classical",
    "talk",
    "hits",
    "radio",
    "entretenimiento",
    "dance",
    "oldies",
    "estación",
    "80s",
    "méxico",
    "fm",
    "christian",
    "public radio",
    "jazz",
    "música",
    "top 40",
    "classic hits",
    "90s",
    "community radio",
    "norteamérica",
    "electronic",
    "pop music",
    "adult contemporary",
    "moi merino",
    "classic rock",
    "latinoamérica",
    "español",
    "country",
    "local news",
    "alternative",
];
