name: nix build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: tsirysndr
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build
